/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LayAvatar: typeof import('@layui/layui-vue')['LayAvatar']
    LayBody: typeof import('@layui/layui-vue')['LayBody']
    LayButton: typeof import('@layui/layui-vue')['LayButton']
    LayCard: typeof import('@layui/layui-vue')['LayCard']
    LayCheckbox: typeof import('@layui/layui-vue')['LayCheckbox']
    LayCheckboxGroup: typeof import('@layui/layui-vue')['LayCheckboxGroup']
    LayCol: typeof import('@layui/layui-vue')['LayCol']
    LayDropdown: typeof import('@layui/layui-vue')['LayDropdown']
    LayDropdownMenu: typeof import('@layui/layui-vue')['LayDropdownMenu']
    LayDropdownMenuItem: typeof import('@layui/layui-vue')['LayDropdownMenuItem']
    LayEmpty: typeof import('@layui/layui-vue')['LayEmpty']
    LayForm: typeof import('@layui/layui-vue')['LayForm']
    LayFormItem: typeof import('@layui/layui-vue')['LayFormItem']
    LayHeader: typeof import('@layui/layui-vue')['LayHeader']
    LayInput: typeof import('@layui/layui-vue')['LayInput']
    LayInputNumber: typeof import('@layui/layui-vue')['LayInputNumber']
    LayLayer: typeof import('@layui/layer-vue')['LayLayer']
    LayLayout: typeof import('@layui/layui-vue')['LayLayout']
    LayLogo: typeof import('@layui/layui-vue')['LayLogo']
    LayMenu: typeof import('@layui/layui-vue')['LayMenu']
    LayMenuItem: typeof import('@layui/layui-vue')['LayMenuItem']
    LayOption: typeof import('@layui/layui-vue')['LayOption']
    LayPagination: typeof import('@layui/layui-vue')['LayPagination']
    LayRow: typeof import('@layui/layui-vue')['LayRow']
    LaySelect: typeof import('@layui/layui-vue')['LaySelect']
    LaySelectOption: typeof import('@layui/layui-vue')['LaySelectOption']
    LaySide: typeof import('@layui/layui-vue')['LaySide']
    LaySubMenu: typeof import('@layui/layui-vue')['LaySubMenu']
    LaySwitch: typeof import('@layui/layui-vue')['LaySwitch']
    LayTabItem: typeof import('@layui/layui-vue')['LayTabItem']
    LayTable: typeof import('@layui/layui-vue')['LayTable']
    LayTabPane: typeof import('@layui/layui-vue')['LayTabPane']
    LayTabs: typeof import('@layui/layui-vue')['LayTabs']
    LayTag: typeof import('@layui/layui-vue')['LayTag']
    LayTextarea: typeof import('@layui/layui-vue')['LayTextarea']
    LayUpload: typeof import('@layui/layui-vue')['LayUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
