// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LayButton: typeof import('@layui/layui-vue')['LayButton']
    LayCard: typeof import('@layui/layui-vue')['LayCard']
    LayCheckbox: typeof import('@layui/layui-vue')['LayCheckbox']
    LayCheckboxGroup: typeof import('@layui/layui-vue')['LayCheckboxGroup']
    LayDatePicker: typeof import('@layui/layui-vue')['LayDatePicker']
    LayForm: typeof import('@layui/layui-vue')['LayForm']
    LayFormItem: typeof import('@layui/layui-vue')['LayFormItem']
    LayIcon: typeof import('@layui/layui-vue')['LayIcon']
    LayInput: typeof import('@layui/layui-vue')['LayInput']
    LayInputNumber: typeof import('@layui/layui-vue')['LayInputNumber']
    LayLayer: typeof import('@layui/layui-vue')['LayLayer']
    LayPagination: typeof import('@layui/layui-vue')['LayPagination']
    LaySelect: typeof import('@layui/layui-vue')['LaySelect']
    LaySelectOption: typeof import('@layui/layui-vue')['LaySelectOption']
    LaySwitch: typeof import('@layui/layui-vue')['LaySwitch']
    LayTabPane: typeof import('@layui/layui-vue')['LayTabPane']
    LayTabs: typeof import('@layui/layui-vue')['LayTabs']
    LayTable: typeof import('@layui/layui-vue')['LayTable']
    LayTableColumn: typeof import('@layui/layui-vue')['LayTableColumn']
    LayTag: typeof import('@layui/layui-vue')['LayTag']
    LayTextarea: typeof import('@layui/layui-vue')['LayTextarea']
    LayUpload: typeof import('@layui/layui-vue')['LayUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
} 